#define COMBO_VARIABLE_LEN
#define COMBO_TERM 35
#define COMBO_STRICT_TIMER

#define LSPO_KEYS KC_LEFT_SHIFT, KC_LSFT, KC_9
#define RSPC_KEYS KC_RIGHT_SHIFT, KC_RSFT, KC_0
#define LCPO_KEYS KC_LEFT_CTRL, KC_TRANSPARENT, KC_LEFT_BRACKET
#define RCPC_KEYS KC_RIGHT_CTRL, KC_TRANSPARENT, KC_RIGHT_BRACKET

#define MK_3_SPEED
