RGB_MATRIX_CUSTOM_USER = no

VPATH  +=  keyboards/gboards/
COMBO_ENABLE=yes

DEFERRED_EXEC_ENABLE = yes

DYNAMIC_TAPPING_TERM_ENABLE = yes

STENO_ENABLE = yes
STENO_PROTOCOL = geminipr
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
NKRO_ENABLE = no
